load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "locality",
    srcs = [
        "components.h",
        "main.cpp",
    ],
    deps = [
        "@eigen",
        "@flecs",
    ],
)

cc_binary(
    name = "locality2",
    srcs = [
        "components.h",
        "main2.cpp",
    ],
    deps = [
        "@eigen",
        "@flecs",
    ],
)

cc_binary(
    name = "locality3",
    srcs = [
        "components.h",
        "main3.cpp",
    ],
    deps = [
        "@eigen",
        "@flecs",
    ],
)

cc_binary(
    name = "locality4",
    srcs = [
        "components.h",
        "main4.cpp",
    ],
    deps = [
        "@eigen",
        "@flecs",
        "@google_benchmark//:benchmark",
    ],
)
