/*
[BIG PICTURE]

0. maintain and update the acceleration structure of my choice

find_neighbors(float radius)?
is_neighbors()?
update_kd_tree()?

1. compute forces
    for each boid i:
        f_sepa, f_align, f_cohesion = 0;
        for each boid j:
            f_sepa += compute_separation_forces(i,j);    // collision avoidance
            f_align += compute_alignment_forces(i,j);    // velocity matching
            f_cohesion += compute_cohesion_forces(i,j);  // centering
        end
    end

1. compute forces (accerlated)
    for each boid i:
        f_sepa, f_align, f_cohesion = 0;
        neighbors = find_neighbors(i);
        for each boid : neighbors
            f_sepa += compute_separation_forces(i,j);
            f_align += compute_alignment_forces(i,j);    // velocity matching
            f_cohesion += compute_cohesion_forces(i,j);  // centering
        end

        // add some special force here maybe
    end

2. apply forces
    for each boid i:
        f[i] = f_sepa + f_align + f_cohesion;
        a[i] = m_inv[i] * f[i];
        v[i] = v[i] + a[i] * dt;
        p[i] = p[i] + v[i] * dt;
    end

3. render boids
    for each boid i:
        draw_boid(i);
    end

*/

// empty structure. it's a tag.
// to be used in a system (query) like this:
// ecs.system<Position, Velocity, ...>.with<Boid>().each([](){});
interface Boid {} 

interface BoidProps {
    attributes{
        vec3 position;
        vec3 velocity;
        vec4 orientation;

        float mass;
        float size;
        
        // TODO: what more do i need?
    }
}

interface AABB {
    attribute vec3 min;
    attribute vec3 max;

    aabb();
    aabb(vec3 min, vec3 max);

    aabb operator=(aabb other);

    static boolean point_in_aabb(aabb a, vec3 p);
    static void corner_point(aabb a, int i, out vec3 p);
    static boolean intersection(aabb a1, aabb a2);
};

// Systems
interface System {
    // pre physics
    void update_acceleration_structure(); // for all body

    // physics
    void step() {
        void compute_separation_force();
        void compute_alignment_force();
        void compute_cohesion_force();
        ...
    }


    // post update
    void draw_boid(); // for all boids
    void draw_body(); // for all body
    void handle_keypress();
}