interface model {
    void build();
    void add_particle();
    void add_rigidbody();
    void add_joint();
    void add_constraint();
}

interface Transform {
    attribute float4x4 matrix;
    attribute float3 position;
    attribute quaternion rotation;
    attribute float3 scale;

    void Transform();

    void setMatrix(float4x4 matrix);
    void setPosition(float3 position);
    void setRotation(quaternion rotation);
    void setScale(float3 scale);

    float4x4 getMatrix();
    float3 getPosition();
    quaternion getRotation();
    float3 getScale();
};

interface Window {
    attribute GLFWwindow* handle;

    [Constant]
    readonly attribute flecs::entity entity;


}

interface Renderer {
    void updateSwapchain();
    void render();

}

interface VertexShader {
    [SetterThrows]
    attribute String src;

    ShaderKind kind;
}

[Constructor(DOMString url, URL base),
 Constructor(DOMString url, optional DOMString base),
 Exposed=(Window,Worker)]
interface ShaderProgram {
    constructor(DOMString str);

    [Throws] constructor(DOMString str);

    [Throws]
    void compile();

    [Throws]
    void link(VertexShader vs);

    [System]
    void updateUniforms();

    [System]
    void updateAttributes();
}

interface Integrator {
    void update();
    void simulate();
    void 
}

XPBDIntegrator implements Integrator;
ImplicitEulerIntegrator implements Integrator;
ImplicitNewmarkIntegrator implements Integrator;
ImplicitMidpointIntegrator implements Integrator;
ExplicitEuler
SimplecticEuler
RungeKuttaIntegrator

XPBDVolumeConstraint implements constraint;
FEMVolumeConstraint